### ISSUE TITLE
Broken on Mavericks

### ISSUE THREAD

**Issue by joesolly** [jkwatson/Muse-Controller#15]
The OSX version of Muse appears to be broken on Mavericks; I can't even get the application to launch.

**Comment by jkwatson** [comment]
Hi Joe.  Do you have Java installed? I understand that the Mavericks installation removes Java (I haven't installed Mavericks anywhere yet, myself).

**Comment by joesolly** [comment]
Hi John,

Thanks for the quick response. I just installed Java 7.45 and it still
isn't opening. I'm not sure what is going on since the application just
seems to refuse to open in any way, it doesn't even give a failure response.

Joe

**Comment by jkwatson** [comment]
Is there anything in the Console.app logs?  I'll probably get to Mavericks this weekend, and can take a look in more detail, then. 

John

**Comment by joesolly** [comment]
John,

Nope. Nothing in the log when I try to launch it. Just let me know when you
get it working on Mavericks, no rush.

Thanks,
Joe

**Comment by jkwatson** [comment]
Have you tried doing a clean install of Muse Controller?  Perhaps
permissions got messed up, or something (just guessing wildly at the
moment, obviously).

**Comment by joesolly** [comment]
Yes I did.

**Comment by joesolly** [comment]
John,

My fault. I guess I have too many windows opened. As I was closing
everything to end my day today, there was a window saying Java 6 had to be
installed (I had installed 7). After that, it worked fine, although it
didn't recognize the app as valid again and i had to allow your unknown app.

Thanks,
Joe

On Fri, Oct 25, 2013 at 10:22 AM, Joseph Solomon <joseph.solomon89@gmail.com

> wrote:
> 
> Yes I did.
>

**Comment by jkwatson** [comment]
No worries. Glad it's working.  Apple does their darnedest to make Java
hard to use.  Enjoy!
